#!/usr/bin/env python3
import os
import sys

PROJECT_DIR = os.path.dirname(os.path.abspath(__file__))

def generate_shards_config(num_shards, replicas_per_shard):
    """Generate shards.config for each replica to enable cross-shard communication."""
    for shard in range(num_shards):
        for replica in range(replicas_per_shard):
            config_dir = os.path.join(PROJECT_DIR, f"shard{shard}", f"replica{replica}", "config")
            shards_config_path = os.path.join(config_dir, "shards.config")

            with open(shards_config_path, "w") as f:
                f.write(f"# Shard topology for shard {shard}, replica {replica}\n")
                f.write("# Auto-generated by generate_shard_hosts.py\n\n")
                f.write(f"system.shards.count = {num_shards}\n")
                f.write(f"system.shards.basePath = {PROJECT_DIR}\n\n")

                # Each shard's config points to replica 0's config directory
                # (all replicas in a shard have the same hosts.config)
                for s in range(num_shards):
                    f.write(f"shard.{s}.configHome = shard{s}/replica0/config\n")

                f.write("\n# Retry configuration\n")
                f.write("system.shards.maxRetries = 3\n")
                f.write("system.shards.retryDelayMs = 1000\n")

            print(f"Generated {shards_config_path}")

def generate_hosts(num_shards, replicas_per_shard, base_ip="127.0.0.1", base_client_port=11000):
    for shard in range(num_shards):
        shard_folder = os.path.join(PROJECT_DIR, f"shard{shard}")
        os.makedirs(shard_folder, exist_ok=True)

        for replica in range(replicas_per_shard):
            replica_folder = os.path.join(shard_folder, f"replica{replica}")
            os.makedirs(replica_folder, exist_ok=True)
            print(f"REPLICA FOLDER: {replica_folder}")
            hosts_file = os.path.join(replica_folder, "config/hosts.config")
            print(hosts_file)
            with open(hosts_file, "w") as f:
                f.write(f"# Hosts file for shard {shard}, replica {replica}\n")
                f.write("# Format: id ip clientPort replicaPort grpcPort\n\n")

                # write all replicas of the shard
                for r in range(replicas_per_shard):
                    replica_id = r
                    client_port = base_client_port + shard*1000 + r*10
                    replica_port = base_client_port + shard*1000 + r*10 + 1
                    grpc_port = 50051 + shard*100 + r
                    f.write(f"{replica_id} {base_ip} {client_port} {replica_port} {grpc_port}\n")

                # Add a reconfiguration/learner client entry
                rc_id = 7000 + shard
                rc_port = 20000 + shard
                f.write(f"\n# Reconfiguration / learner client\n")
                f.write(f"{rc_id} {base_ip} {rc_port}\n")

            print(f"Generated {hosts_file}")


if __name__ == "__main__":
    if len(sys.argv) != 3:
        print("Usage: python3 generate_shard_hosts.py <num_shards> <replicas_per_shard>")
        sys.exit(1)

    num_shards = int(sys.argv[1])
    replicas_per_shard = int(sys.argv[2])

    generate_hosts(num_shards, replicas_per_shard)
    generate_shards_config(num_shards, replicas_per_shard)
